INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (1, 1, N'Kanapka z szynka', N'Szybie sniadanie dla glodych ludzi');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (2, 1, N'Kanapka z serem', N'Dla wegetarianów');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (3, 1, N'Tosty z szynka', N'Idealne na sniadanie');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (4, 1, N'Tosty z serem', N'Idealne na sniadanie wegetarianskie');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (5, 2, N'Woda', N'Ochlody ci doda');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (6, 2, N'Pepsi', N'Nieco slodkosci');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (7, 2, N'Coca cola', N'Slodki napój');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (8, 2, N'Mirinda', N'Slodki napój');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (9, 2, N'Fanta', N'Slodki napój');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (10, 2, N'Sprite', N'Slodki napój');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (11, 2, N'Mountain Dew', N'Slodki napój');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (12, 3, N'Jajko w koszulce', N'Smakuje i wyglada');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (13, 3, N'Maca', N'Taka roslina');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (14, 16, N'Zupa pomidorowa', N'Pyszna, gesta zupa pomidorowa z dodatkiem smietany i bazylii.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (15, 16, N'Zupa cebulowa', N'Klasyczna, aromatyczna zupa cebulowa z grzankami.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (16, 16, N'Zupa krem z brokulów', N'Lekka, kremowa zupa z brokulów z dodatkiem galki muszkatolowej.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (17, 16, N'Zupa gulaszowa', N'Gesta zupa gulaszowa z kluskami slaskimi.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (18, 16, N'Zupa ogórkowa', N'Chlodnik ogórkowy z dodatkiem koperku i jogurtu.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (19, 3, N'Krewetki z rozna', N'Krekwetki marynowane w sosie dyniowym z chrupiaca skórka');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (20, 3, N'Bruschetta', N'Chleb tostowy z pomidorami, bazylia i oliwa z oliwek.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (21, 3, N'Tatar z poledwicy', N'Poledwica mielona na surowo z cebula, jajkiem i kaparami.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (22, 6, N'Salatka grecka', N'Salatka z pomidorów, oliwek, cebuli, ogórków i fety.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (23, 6, N'Salatka Caesar', N'Salatka z kurczakiem, croutonami, sosiem Caesar i parmezanem.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (24, 3, N'Tosty z awokado', N'Tosty z awokado, jajkiem i szczypiorkiem.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (25, 3, N'Carpaccio z poledwicy', N'Cienko pokrojona, surowa poledwica z sosem winegret i parmezanem.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (26, 3, N'Fondue', N'Tradycyjne fondue serowe z chlebem i warzywami do maczania.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (27, 3, N'Tosty z kremem z ciecierzycy', N'Tosty z kremem z ciecierzycy, pomidorem i oliwkami.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (28, 3, N'Antipasti misti', N'Mieszanka wloskich przystawek: szynka parmenska, kielbasa, sery, oliwki i warzywa.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (29, 4, N'Margherita', N'Pizza z pomidorami, mozzarella i bazylia.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (30, 4, N'Pepperoni', N'Pizza z pepperoni i serem mozzarella.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (31, 4, N'Quattro stagioni', N'Pizza z kurczakiem, pieczarkami, anchois i kaparami.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (32, 4, N'Vegetariana', N'Pizza z cukinia, papryka, cebula, pieczarkami i serem feta.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (33, 4, N'Hawajska', N'Pizza z kurczakiem, ananasem i serem mozzarella.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (34, 5, N'Lody waniliowe', N'Klasyczne, rozplywajace sie lody waniliowe z sosem malinowym.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (35, 5, N'Tiramisu', N'Klasyczne tiramisu z biszkoptami, mascarpone i kawa.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (36, 5, N'Sernik z brzoskwiniami', N'Klasyczny sernik z brzoskwiniami i kruszonka.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (37, 5, N'Lody z bita smietana', N'Lody z ulubionymi owocami i bita smietana.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (38, 5, N'Panna cotta', N'Kremowa panna cotta z truskawkami i polewa czekoladowa.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (39, 7, N'Spaghetti Carbonara', N'Spaghetti z kremowym sosem Carbonara z boczkiem i jajkiem.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (40, 7, N'Tagliatelle Bolognese', N'Tagliatelle z klasycznym sosem Bolognese z miesem mielonym.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (41, 7, N'Gnocchi z sosem pomidorowym', N'Gnocchi z pomidorami, bazylia i serem mozzarella.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (42, 7, N'Lasagne z warzywami', N'Lasagne z warzywami, serem i beszamelem.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (43, 7, N'Ravioli z kremowym sosem ziemniaczanym', N'Ravioli z farszem z ricotty i sosem ziemniaczanym.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (44, 6, N'Salatka z surimi', N'Salatka z surimi, kukurydza, majonezem i ogórkiem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (45, 6, N'Salatka jarzynowa', N'Salatka z groszkiem, jablkiem, ziemniakami i marchewka');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (46, 6, N'Salatka z kurczakiem i awokado', N'Salatka z kurczakiem, awokado, pomidorami, kukurydza i salsa ranch.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (47, 6, N'Salatka z wedzonym lososiem', N'Salatka z wedzonym lososiem, jajkiem, ogórkiem i cebula.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (48, 6, N'Salatka coleslaw', N'Salatka z marchewki, kapusty i sosu mayo.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (49, 8, N'Filet z dorsza', N'Pieczony filet z dorsza z warzywami i ziemniakami.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (50, 8, N'Halibut z grilla', N'Halibut z grilla z salsa z mango i rukola.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (51, 8, N'Tosty z lososiem', N'Tosty z lososiem, awokado i jajkiem.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (52, 8, N'Krewetki na grillu', N'Krewetki marynowane w sosie cytrynowym i grillowane na ruszcie.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (53, 8, N'Sushi', N'Zestaw sushi z róznymi farszami: lososiem, tunczykiem, krewetkami i awokado.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (54, 9, N'Koktajl z awokado', N'Koktajl z awokado, szpinakiem, bananem i mlekiem kokosowym.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (55, 9, N'Zapiekanka z cukinii', N'Zapiekanka z cukinii, pieczarek i serem feta.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (56, 9, N'Falafel w platkach', N'Falafel w platkach z salatka, salsa tahini i hummusem.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (57, 9, N'Salatka z quinoa', N'Salatka z quinoa, pomidorami, papryka i serem feta.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (58, 9, N'Hummus z pomidorem i kielbasa', N'Hummus z pomidorem i kielbasa z grillowanymi warzywami.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (59, 10, N'Stek z Poledwicy', N'Stek z Poledwicy z ziemniakami i warzywami.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (60, 10, N'Kurczak z grilla', N'Kurczak z grilla z sosem BBQ i frytkami.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (61, 10, N'Kotlety mielone', N'Kotlety mielone z ziemniakami i surówka.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (62, 10, N'Karkówka z grilla', N'Karkówka z grilla z warzywami i rösti.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (63, 10, N'Burgery z wolowina', N'Burgery z wolowina, serem, ketchupem i warzywami.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (64, 11, N'Mojito', N'Klasyczny koktajl z rumem, mieta, cukrem i limonka.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (65, 11, N'Margarita', N'Koktajl z tequila, Cointreau i sokiem z cytryny.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (66, 11, N'Koktajl pomaranczowy', N'Koktajl z sokiem pomaranczowym, mlekiem i lodem.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (67, 11, N'Koktajl bananowy', N'Koktajl z bananami, mlekiem, cukrem i lodem.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (68, 11, N'Koktajl truskawkowy', N'Koktajl z truskawkami, jogurtem, mlekiem i lodem.');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (69, 12, N'Espresso', N'Intensywny, wytrawny i aromatyczny klasyczny wloski kawa');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (70, 12, N'Flat White', N'Klasyczny australijski kawa z mlekiem o gestej, aksamitnej pianie');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (71, 12, N'Latte', N'Klasyczna amerykanska kawa z mlekiem i delikatna warstwa piany');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (72, 12, N'Cappuccino', N'Wloska kawa z mlekiem, mocno spienionym i delikatna warstwa kakao');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (73, 12, N'Black Coffee', N'Czysta, mocna kawa bez mleka');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (74, 12, N'Iced Coffee', N'Kawa mrozona z lodem, mlekiem i syropem smakowym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (75, 12, N'Cold Brew', N'Mocna, chlodna kawa przygotowywana metoda zimnego parzenia');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (76, 12, N'Turkish Coffee', N'Mocna, aromatyczna kawa parzona na specjalnym ruszcie');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (77, 12, N'Instant Coffee', N'Szybko parzona kawa rozpuszczalna');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (78, 12, N'Decaf Coffee', N'Kawa bezkofeinowa, o nizszej zawartosci kofeiny');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (79, 12, N'Organic Coffee', N'Ekologiczna, certyfikowana kawa');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (80, 12, N'Specialty Coffee', N'Unikalne, wysokiej jakosci kawy pochodzace z wybranych regionów swiata');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (81, 12, N'Single Origin Coffee', N'Kawa pochodzaca z jednego konkretnego regionu');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (82, 12, N'Blended Coffee', N'Mieszanka kilku gatunków kawy');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (83, 12, N'Black Tea', N'Mocna, aromatyczna herbata czarna, o dlugim czasie parzenia');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (84, 12, N'Green Tea', N'Lekka, orzezwiajaca herbata zielona, o krótkim czasie parzenia');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (85, 12, N'White Tea', N'Delikatna, subtelna herbata biala, o krótkim czasie parzenia');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (86, 12, N'Oolong Tea', N'Herbata oolong o srednim stopniu fermentacji, o wyrazistym smaku i aromacie');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (87, 12, N'Herbata Czerwona', N'Herbata czerwona, o delikatnym smaku i lekko slodkawym aromacie');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (88, 12, N'Herbata Owocowa', N'Herbata owocowa z dodatkiem owoców lub owocowych aromatów');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (89, 12, N'Herbata Ziolowa', N'Herbata ziolowa z dodatkiem ziól lub ziolowych aromatów');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (90, 12, N'Herbata Mrozona', N'Herbata mrozona z dodatkiem lodu i syropów smakowych');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (91, 13, N'Cheeseburger', N'Klasyczny burger z kotletem, serem i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (92, 13, N'Hamburger', N'Klasyczny burger z kotletem i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (93, 13, N'Bacon Cheeseburger', N'Burger z kotletem, bekonem, serem i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (94, 13, N'Veggie Burger', N'Wegetarianski burger z warzywami i specjalnym kotletem wegetarianskim');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (95, 13, N'Chicken Burger', N'Burger z kurczakiem i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (96, 13, N'Turkey Burger', N'Burger z indykiem i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (97, 13, N'Lamb Burger', N'Burger z jagniecego kotleta i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (98, 13, N'Fish Burger', N'Burger z kotletem rybnym i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (99, 13, N'Black Bean Burger', N'Wegetarianski burger z fasola czarna i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (100, 13, N'Portobello Mushroom Burger', N'Wegetarianski burger z pieczarka portobello i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (101, 13, N'Slider', N'Maly, klasyczny burger z kotletem i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (102, 13, N'Double Burger', N'Podwójny burger z dwoma kotletami i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (103, 13, N'Triple Burger', N'Potrójny burger z trzema kotletami i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (104, 14, N'Tortilla z kurczakiem', N'Tortilla z kurczakiem, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (105, 14, N'Tortilla z wolowina', N'Tortilla z wolowina, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (106, 14, N'Tortilla z krewetkami', N'Tortilla z krewetkami, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (107, 14, N'Tortilla z indykiem', N'Tortilla z indykiem, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (108, 14, N'Tortilla z jagniecina', N'Tortilla z jagniecina, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (109, 14, N'Tortilla z ryba', N'Tortilla z ryba, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (110, 14, N'Tortilla z fasola', N'Wegetarianska tortilla z fasola, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (111, 14, N'Tortilla z pieczarkami', N'Wegetarianska tortilla z pieczarkami, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (112, 14, N'Tortilla z warzywami', N'Wegetarianska tortilla z róznymi warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (113, 14, N'Tortilla z kaczka', N'Tortilla z kaczka, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (114, 14, N'Tortilla z królikiem', N'Tortilla z królikiem, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (115, 14, N'Tortilla z jajkiem', N'Tortilla z jajkiem, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (116, 14, N'Tortilla z kielbasa', N'Tortilla z kielbasa, warzywami i specjal');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (117, 15, N'Kebab z kurczakiem', N'Kebab z kurczakiem, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (118, 15, N'Kebab z ciecierzyca', N'Wegetarianski kebab z ciecierzyca, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (119, 15, N'Kebab z miesem', N'Kebab z miesem, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (120, 15, N'Kebab z indykiem', N'Kebab z indykiem, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (121, 15, N'Kebab z jagniecina', N'Kebab z jagniecina, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (122, 15, N'Kebab z baranina', N'Kebab z baranina, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (123, 15, N'Kebab z ryba', N'Kebab z ryba, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (124, 15, N'Kebab z kaczka', N'Kebab z kaczka, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (125, 15, N'Kebab z królikiem', N'Kebab z królikiem, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (126, 15, N'Kebab z czerwonym miesem', N'Kebab z czerwonym miesem, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (127, 15, N'Kebab z bialym miesem', N'Kebab z bialym miesem, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (128, 15, N'Kebab z falafel', N'Wegetarianski kebab z falafel, warzywami i specjalnym sosem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (129, 15, N'Kebab z tofu', N'Wegetarianski kebab z tofu');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (130, 5, N'Ciastko czekoladowe', N'Pyszne ciastko z kremem czekoladowym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (131, 5, N'Lodowe lody', N'Lodowe lody o smaku waniliowym z bita smietana');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (132, 5, N'Szarlotka', N'Slodkie ciasto z jablkami i kruszonka');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (133, 5, N'Sernik', N'Slodki sernik z galaretka i owocami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (134, 5, N'Paczki z marmolada', N'Paczki z miekkiego ciasta z nadzieniem marmoladowym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (136, 11, N'Daiquiri', N'Koktajl z rumu, limonki i cukru trzcinowego');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (137, 11, N'Piña Colada', N'Koktajl z rumu, kokosu i ananasa');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (138, 11, N'Tequila Sunrise', N'Koktajl z tequili, pomaranczy i grenadiny');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (139, 11, N'Bloody Mary', N'Koktajl z wódki, soku z pomidorów i przypraw');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (140, 11, N'Whiskey Sour', N'Koktajl z whiskey, soku z cytryny i cukru trzcinowego');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (141, 11, N'Sex on the Beach', N'Koktajl z wódki, soku z brzoskwini, grenadiny i soku z pomaranczy');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (142, 11, N'Long Island Iced Tea', N'Koktajl z wódki, tequili, ginu, likieru triple sec, soku z cytryny i coca-coli');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (143, 7, N'Pesto z makaronem', N'Makaron z sosem z bazylii i orzechów');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (144, 7, N'Alfredo', N'Makaron z sosem smietanowo-serem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (145, 7, N'Krem z makaronem i pomidorami', N'Makaron z kremowym sosem pomidorowym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (146, 7, N'Makaron z krewetkami', N'Makaron z krewetkami i sosem cytrynowym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (147, 7, N'Makaron z kurczakiem i pieczarkami', N'Makaron z kurczakiem i pieczarkami w sosie smietanowym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (148, 7, N'Makaron z cukinia i pomidorami', N'Makaron z cukinia i pomidorami w lekkim sosie pomidorowym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (149, 7, N'Makaron z kurczakiem i ananasem', N'Makaron z kurczakiem i ananasem w sosie curry');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (150, 10, N'Kotlet schabowy', N'Cienki kotlet ziemniaczany z panierka i kapusta');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (151, 10, N'Golonka z piekarnika', N'Golonka z piekarnika z warzywami i ziemniakami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (152, 10, N'Kielbasa z grilla', N'Kielbasa z grilla z pieczarkami i cebula');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (153, 10, N'Szaszlyk z kurczaka', N'Szaszlyk z kurczaka z warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (154, 10, N'Kurczak z piekarnika', N'Kurczak z piekarnika z ziemniakami i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (155, 10, N'Piers z indyka z grillowanymi warzywami', N'Piers z indyka z grillowanymi warzywami i pieczonymi ziemniakami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (156, 2, N'Sok jablkowy', N'Swiezo wyciskany sok jablkowy');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (157, 2, N'Sok pomaranczowy', N'Swiezo wyciskany sok pomaranczowy');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (158, 2, N'Sok grejpfrutowy', N'Swiezo wyciskany sok grejpfrutowy');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (159, 2, N'Sok z aronii', N'Sok z aronii z dodatkiem cukru');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (160, 2, N'Sok z granatów', N'Sok z granatów z dodatkiem cukru');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (161, 2, N'Mors', N'Napój z owoców');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (162, 1, N'Baguette', N'Dlugi, cienki bochenek chleba z ziarnami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (163, 1, N'Chleb pszenny', N'Klasyczny bialy chleb z maki pszennej');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (164, 1, N'Chleb zytni', N'Chleb zytni o ciemnej barwie');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (165, 1, N'Chleb razowy', N'Chleb razowy o korzystnym dla zdrowia skladzie');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (166, 1, N'Croissanty', N'Male, rozwalkowane kajzerki z ciasta francuskiego');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (167, 1, N'Chleb orkiszowy', N'Chleb orkiszowy o wyjatkowym smaku i korzystnym dla zdrowia skladzie');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (169, 4, N'Pizza hawajska', N'Cienki spód pizzy z szynka, ananasem i serem mozzarella');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (170, 4, N'Warzywna', N'Cienki spód pizzy z grillowanymi warzywami, sosem pomidorowym i serem mozzarella');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (171, 4, N'Pizza z kurczakiem BBQ', N'Cienki spód pizzy z sosem BBQ, grillowanym kurczakiem, cebula i serem cheddar');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (172, 4, N'Pizza z kielbasa', N'Cienki spód pizzy z kielbasa, pieczarkami i sosem pomidorowym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (173, 4, N'Pizza z tunczykiem', N'Cienki spód pizzy z tunczykiem, cebula i oliwkami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (174, 4, N'Pizza z serem feta', N'Cienki spód pizzy z pieczarkami, papryka, cebula i serem feta');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (175, 8, N'Owsianka z krewetkami', N'Owsianka z krewetkami, cebula i sosem smietanowym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (176, 8, N'Koktajl z krewetek', N'Koktajl z krewetek, awokado, pomidorem i sokiem z cytryny');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (177, 8, N'Klopsiki rybne', N'Klopsiki rybne z cebula i ziolami, podane z ziemniakami i surówka');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (178, 8, N'Zapiekanka z makreli', N'Zapiekanka z makreli, cebuli, pomidorów i serem feta');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (179, 8, N'Risotto z kalmarami', N'Risotto z kalmarami i warzywami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (180, 6, N'Salatka z krewetkami', N'Salatka z krewetkami, papryka, cebula, oliwkami i sosem vinaigrette');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (181, 6, N'Salatka z ciecierzyca', N'Salatka z ciecierzyca, papryka, cebula, pomidorem i serem feta');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (182, 6, N'Salatka z fasola', N'Salatka z fasola, kukurydza, pomidorem, serem feta i sosem vinegrette');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (183, 6, N'Salatka z rukola', N'Salatka z rukola, kozim serem, pestkami dyni i sosem balsamicznym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (184, 6, N'Salatka z kasza', N'Salatka z kasza gryczana, warzywami, kurczakiem i sosem jogurtowym');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (186, 6, N'Salatka z jajkiem', N'Salatka z jajkiem, salata, pomidorem, kielbasa i serem cheddar');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (187, 9, N'Zapiekanka warzywna', N'Pyszna i sycaca zapiekanka z warzywami i serem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (188, 9, N'Falafel', N'Kulki z ciecierzycy i warzyw zapiekane w glebokim tluszczu');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (189, 9, N'Kotlety sojowe', N'Kotlety z soi i warzyw');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (190, 9, N'Kurczak z soi', N'Kurczak z soi i warzyw');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (191, 9, N'Kurczak z kaszy jaglanej', N'Kurczak z kaszy jaglanej i warzyw');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (192, 9, N'Nalesniki z warzywami', N'Pyszne nalesniki z warzywami i serem');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (193, 16, N'Zupa jarzynowa', N'Zupa z warzywami i ziemniakami');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (195, 16, N'Zupa fasolowa', N'Pyszna i pozywna zupa fasolowa z dodatkiem warzyw');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (196, 16, N'Zupa kalafiorowa', N'Smaczna i sycaca zupa kalafiorowa z dodatkiem kremówki');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (197, 16, N'Zupa czerwona fasola', N'Zupa z czerwonej fasoli i warzyw');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (198, 16, N'Zupa soczewica', N'Pyszna i pozywna zupa z soczewicy i warzyw');
INSERT INTO u_sus.dbo.Product (ProductID, CategoryID, ProductName, Description) VALUES (199, 16, N'Zupa z kaszy jaglanej', N'Smaczna i sycaca zupa z kaszy jaglanej i warzyw');
